# -*- coding: utf-8 -*-
"""Siamese Encoder Model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nd1xxuHSVKbwX-7RN_qZTG2XKKvbFtFO


from google.colab import files
files.upload()

import pickle

with open("music_features_colab.pkl", "rb") as f:
    raw = pickle.load(f) 

print("Tracks:", len(raw))
print("Feature dim:", next(iter(raw.values())).shape)

!pip install torch numpy

import torch
import torch.nn as nn
import torch.nn.functional as F

class MusicEncoder(nn.Module):
    def __init__(self, input_dim=1570):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(input_dim, 512),
            nn.BatchNorm1d(512),
            nn.ReLU(),
            nn.Dropout(0.3),

            nn.Linear(512, 256),
            nn.ReLU(),

            nn.Linear(256, 128),
            nn.ReLU(),

            nn.Linear(128, 64)
        )

    def forward(self, x):
        return F.normalize(self.net(x), dim=1)

import pickle
import random
from torch.utils.data import Dataset, DataLoader

with open("music_features_colab.pkl", "rb") as f:
    raw = pickle.load(f)

features = {k: torch.tensor(v) for k,v in raw.items()}
track_ids = list(features.keys())

class TripletDataset(Dataset):
    def __len__(self):
        return len(track_ids) * 5

    def __getitem__(self, idx):
        a = random.choice(track_ids)
        n = random.choice([i for i in track_ids if i != a])

        anchor = features[a]
        positive = anchor + torch.randn_like(anchor) * 0.01
        negative = features[n]

        return anchor, positive, negative

dataset = TripletDataset()
loader = DataLoader(dataset, batch_size=32, shuffle=True)

model = MusicEncoder()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

for epoch in range(30):
    total_loss = 0
    for a,p,n in loader:
        ea, ep, en = model(a), model(p), model(n)

        loss = torch.relu(
            torch.nn.functional.pairwise_distance(ea, ep) -
            torch.nn.functional.pairwise_distance(ea, en) + 1.0
        ).mean()

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch {epoch+1}: {total_loss/len(loader):.4f}")

torch.save(model.state_dict(), "music_siamese_encoder.pth")

import torch
import torch.nn.functional as F
import random

model.eval()

ids = list(features.keys())

a = torch.tensor(features[random.choice(ids)])
p = a + torch.randn_like(a) * 0.01
n = torch.tensor(features[random.choice(ids)])

with torch.no_grad():
    ea = model(a.unsqueeze(0))
    ep = model(p.unsqueeze(0))
    en = model(n.unsqueeze(0))

print("A–P similarity:", F.cosine_similarity(ea, ep).item())
print("A–N similarity:", F.cosine_similarity(ea, en).item())

torch.save(model.state_dict(), "music_metric_model.pt") """