# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oZjb10bTbOWEvQh2m_2TXbTHXDlTto9-
"""

"""from google.colab import files
files.upload() """

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.metrics.pairwise import cosine_similarity
import matplotlib.pyplot as plt

data = np.load("training_features.npz")

X = data["X"]      # (648, 1591)
ids = data["ids"]  # track IDs

print("X shape:", X.shape)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

pca = PCA(n_components=256, random_state=42)
X_pca = pca.fit_transform(X_scaled)

print("Reduced shape:", X_pca.shape)

from sklearn.neighbors import NearestNeighbors

k = 5  # nearest neighbors
nn = NearestNeighbors(n_neighbors=k+1, metric="cosine")
nn.fit(X_pca)

neighbors = nn.kneighbors(X_pca, return_distance=False)

def build_triplets(X, neighbors, num_triplets=20000):
    triplets = []
    n = X.shape[0]

    for i in range(num_triplets):
        anchor = np.random.randint(0, n)
        positive = np.random.choice(neighbors[anchor][1:])
        negative = np.random.randint(0, n)

        while negative in neighbors[anchor]:
            negative = np.random.randint(0, n)

        triplets.append((anchor, positive, negative))

    return triplets

triplets = build_triplets(X_pca, neighbors)
print("Triplets:", len(triplets))

class SimilarityNet(torch.nn.Module):
    def __init__(self, input_dim=256):
        super().__init__()
        self.net = torch.nn.Sequential(
            torch.nn.Linear(input_dim, 128),
            torch.nn.BatchNorm1d(128),
            torch.nn.ReLU(),
            torch.nn.Linear(128, 64)
        )

    def forward(self, x):
        return torch.nn.functional.normalize(self.net(x), dim=1)

# -----------------------------
# STEP 0 — IMPORTS
# -----------------------------
import numpy as np
import torch
import torch.nn as tnn         # <- renamed to avoid conflict
import torch.nn.functional as F
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.neighbors import NearestNeighbors
from sklearn.metrics.pairwise import cosine_similarity
import matplotlib.pyplot as plt

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Using device:", device)

# -----------------------------
# STEP 1 — LOAD DATA
# -----------------------------
data = np.load("training_features.npz")
X = data["X"]      # (648, 1591)
ids = data["ids"]  # track IDs
print("X shape:", X.shape)

# -----------------------------
# STEP 2 — NORMALIZE & PCA
# -----------------------------
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

pca = PCA(n_components=256, random_state=42)
X_pca = pca.fit_transform(X_scaled)
print("PCA shape:", X_pca.shape)

# -----------------------------
# STEP 3 — NEAREST NEIGHBORS
# -----------------------------
k = 5
nn_model = NearestNeighbors(n_neighbors=k+1, metric="cosine")
nn_model.fit(X_pca)
neighbors = nn_model.kneighbors(X_pca, return_distance=False)

# -----------------------------
# STEP 4 — TRIPLETS FOR SELF-SUPERVISED TRAINING
# -----------------------------
def build_triplets(X, neighbors, num_triplets=20000):
    triplets = []
    n = X.shape[0]
    for _ in range(num_triplets):
        anchor = np.random.randint(0, n)
        positive = np.random.choice(neighbors[anchor][1:])
        negative = np.random.randint(0, n)
        while negative in neighbors[anchor]:
            negative = np.random.randint(0, n)
        triplets.append((anchor, positive, negative))
    return triplets

triplets = build_triplets(X_pca, neighbors)
print("Triplets created:", len(triplets))

# -----------------------------
# STEP 5 — METRIC LEARNING NETWORK
# -----------------------------
class SimilarityNet(tnn.Module):
    def __init__(self, input_dim=256):
        super().__init__()
        self.net = tnn.Sequential(
            tnn.Linear(input_dim, 128),
            tnn.BatchNorm1d(128),
            tnn.ReLU(),
            tnn.Linear(128, 64)
        )

    def forward(self, x):
        return F.normalize(self.net(x), dim=1)

# -----------------------------
# STEP 6 — TRAINING SETUP
# -----------------------------
model = SimilarityNet(input_dim=X_pca.shape[1]).to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
loss_fn = tnn.TripletMarginLoss(margin=0.4)

X_tensor = torch.tensor(X_pca, dtype=torch.float32).to(device)

# -----------------------------
# STEP 7 — TRAINING LOOP
# -----------------------------
epochs = 20
batch_size = 128

for epoch in range(epochs):
    np.random.shuffle(triplets)
    total_loss = 0

    for i in range(0, len(triplets), batch_size):
        batch = triplets[i:i+batch_size]

        a = torch.stack([X_tensor[t[0]] for t in batch])
        p = torch.stack([X_tensor[t[1]] for t in batch])
        n = torch.stack([X_tensor[t[2]] for t in batch])

        optimizer.zero_grad()
        loss = loss_fn(model(a), model(p), model(n))
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch {epoch+1}, Loss: {total_loss:.4f}")

# -----------------------------
# STEP 8 — SAVE LEARNED EMBEDDINGS
# -----------------------------
with torch.no_grad():
    learned_embeddings = model(X_tensor).cpu().numpy()

np.savez_compressed("learned_embeddings.npz", embeddings=learned_embeddings, ids=ids)
print("Saved learned embeddings:", learned_embeddings.shape)

# -----------------------------
# STEP 9 — CALIBRATION (COSINE)
# -----------------------------
sim_matrix = cosine_similarity(learned_embeddings)
upper = sim_matrix[np.triu_indices_from(sim_matrix, k=1)]

mean_sim = upper.mean()
std_sim = upper.std()
print("Cosine similarity mean:", mean_sim, "STD:", std_sim)

# Optional: histogram
plt.hist(upper, bins=50)
plt.title("Similarity Score Distribution")
plt.xlabel("Cosine similarity")
plt.ylabel("Frequency")
plt.show()

import joblib
import os

os.makedirs("models/net", exist_ok=True)

# Save model
torch.save(model.state_dict(), "models/net/similarity_net.pth")
print("✅ Model saved")

# Save scaler & PCA
joblib.dump(scaler, "models/net/scaler.joblib")
joblib.dump(pca, "models/net/pca_256.joblib")
print("✅ Scaler & PCA saved")

# Save similarity stats
np.savez(
    "models/net/sim_stats.npz",
    mean=mean_sim,
    std=std_sim
)
print("✅ Similarity stats saved")

# Save PyTorch model
torch.save(model.state_dict(), "similarity_net.pth")
print("✅ Model saved: similarity_net.pth")

import joblib

# Save PCA
joblib.dump(pca, "pca_256.joblib")
print("✅ PCA saved: pca_256.joblib")

# Save scaler
joblib.dump(scaler, "scaler.joblib")
print("✅ Scaler saved: scaler.joblib")

mean_sim = sim_matrix[np.triu_indices_from(sim_matrix, k=1)].mean()
std_sim = sim_matrix[np.triu_indices_from(sim_matrix, k=1)].std()

np.savez("sim_stats.npz", mean=mean_sim, std=std_sim)
print("✅ Similarity stats saved: sim_stats.npz")